import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BookmarkIcon, TrashIcon } from "@heroicons/react/24/outline";
import { Panel } from "./Panel";
export function HighlightsPanel({ highlights, segments, onRemove }) {
    return (_jsx(Panel, { title: "\u91CD\u70B9\u6807\u8BB0", description: "\u6536\u96C6\u4F1A\u8BAE\u4E2D\u7684\u5173\u952E\u53E5\uFF0C\u65B9\u4FBF\u6574\u7406\u4E0E\u4E8C\u6B21\u7F16\u8F91", className: "lg:col-span-1", action: _jsxs("span", { className: "inline-flex items-center gap-1 rounded-full bg-slate-900/5 px-3 py-1 text-xs font-medium text-slate-500", children: [_jsx(BookmarkIcon, { className: "h-3.5 w-3.5" }), highlights.length, " \u6761"] }), children: highlights.length === 0 ? (_jsxs("div", { className: "flex min-h-[160px] flex-col items-center justify-center gap-2 rounded-2xl border border-dashed border-slate-200 bg-white/60 p-6 text-center text-sm text-slate-500", children: [_jsx("p", { children: "\u6682\u65E0\u91CD\u70B9" }), _jsx("p", { className: "text-xs text-slate-400", children: "\u5728\u5B9E\u65F6\u5B57\u5E55\u4E2D\u70B9\u51FB\u201C\u6807\u8BB0\u91CD\u70B9\u201D\u53EF\u5FEB\u901F\u6DFB\u52A0" })] })) : (_jsx("ul", { className: "flex flex-col gap-3", children: highlights.map((highlight) => {
                const segment = segments.get(highlight.segmentId);
                return (_jsxs("li", { className: "rounded-2xl border border-slate-200/60 bg-white/80 p-4 transition hover:border-primary-200 hover:shadow-sm", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-wide text-primary-500", children: segment?.speaker ?? "Speaker" }), _jsx("p", { className: "mt-1 text-sm text-slate-500", children: segment ? segment.text : highlight.text })] }), _jsx("button", { type: "button", onClick: () => onRemove(highlight.id), className: "rounded-full p-1 text-slate-400 transition hover:bg-slate-100 hover:text-slate-600", children: _jsx(TrashIcon, { className: "h-4 w-4" }) })] }), _jsx("p", { className: "mt-3 text-sm text-slate-400", children: highlight.text })] }, highlight.id));
            }) })) }));
}
