import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Panel } from "./Panel";
export function TranscriptStream({ segments, onHighlight, isStreaming, isLoading = false }) {
    return (_jsx(Panel, { title: "\u5B9E\u65F6\u5B57\u5E55", description: "\u540C\u6B65\u663E\u793A\u8F6C\u5199\u6587\u672C\uFF0C\u53EF\u4E00\u952E\u6807\u8BB0\u91CD\u70B9", action: _jsxs("span", { className: "inline-flex items-center gap-2 rounded-full bg-emerald-100/80 px-3 py-1 text-xs font-semibold text-emerald-600", children: [_jsxs("span", { className: `relative flex h-2.5 w-2.5 items-center justify-center`, children: [_jsx("span", { className: `h-2 w-2 rounded-full ${isStreaming ? "bg-emerald-500" : "bg-slate-300"}` }), isStreaming ? _jsx("span", { className: "absolute inline-flex h-5 w-5 animate-pulse rounded-full bg-emerald-400/40" }) : null] }), isStreaming ? "Streaming" : "Standby"] }), className: "lg:col-span-2", children: _jsx("div", { className: "relative max-h-[320px] overflow-hidden rounded-2xl bg-gradient-to-b from-white via-white to-surface-100", children: _jsx("div", { className: "custom-scroll h-[320px] overflow-y-auto px-4 py-2 pr-2", children: isLoading ? (_jsx("div", { className: "flex h-full flex-col items-center justify-center gap-2 text-sm text-slate-500", children: _jsx("p", { children: "\u8BFB\u53D6\u8F6C\u5199\u6570\u636E\u4E2D..." }) })) : segments.length === 0 ? (_jsxs("div", { className: "flex h-full flex-col items-center justify-center gap-2 text-sm text-slate-500", children: [_jsx("p", { children: "\u5C1A\u65E0\u8F6C\u5199\u5185\u5BB9" }), _jsx("p", { className: "text-xs", children: "\u5F00\u59CB\u5F55\u97F3\u6216\u5BFC\u5165\u97F3\u9891\u5373\u53EF\u770B\u5230\u5B9E\u65F6\u5B57\u5E55" })] })) : (_jsx("ul", { className: "flex flex-col gap-3", children: segments.map((segment) => (_jsxs("li", { className: "group rounded-2xl border border-slate-200/70 bg-white/80 p-3 transition-all duration-200 hover:border-primary-200 hover:shadow-sm", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs font-medium uppercase tracking-wide text-primary-500", children: segment.speaker }), _jsxs("p", { className: "mt-1 text-sm text-slate-600", children: [formatTime(segment.start), " - ", formatTime(segment.end)] })] }), _jsx("button", { type: "button", onClick: () => onHighlight(segment), className: "inline-flex items-center gap-2 rounded-full border border-transparent bg-primary-50 px-3 py-1 text-xs font-semibold text-primary-600 transition group-hover:border-primary-200 group-hover:bg-primary-100", children: "\u6807\u8BB0\u91CD\u70B9" })] }), _jsx("p", { className: "mt-3 text-base text-slate-900", children: segment.text })] }, segment.id))) })) }) }) }));
}
function formatTime(seconds) {
    const minutes = Math.floor(seconds / 60)
        .toString()
        .padStart(2, "0");
    const rest = Math.floor(seconds % 60)
        .toString()
        .padStart(2, "0");
    return `${minutes}:${rest}`;
}
